// Code generated by mockery v2.40.0. DO NOT EDIT.

package mocks

import (
	"context"
	"testing"

	"github.com/stretchr/testify/mock"

	"project-test-primo/internal/domain"
)

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

// NewProductRepository creates a new instance of MockProductRepository.
func NewProductRepository(t *testing.T) *MockProductRepository {
	m := &MockProductRepository{}
	m.Mock.Test(t)
	return m
}

// Create provides a mock function with given fields: ctx, product
func (m *MockProductRepository) Create(ctx context.Context, product *domain.Product) (*domain.Product, error) {
	ret := m.Called(ctx, product)
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Product) (*domain.Product, error)); ok {
		return rf(ctx, product)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Product) *domain.Product); ok {
		return rf(ctx, product), ret.Error(1)
	}
	var r0 *domain.Product
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*domain.Product)
	}
	return r0, ret.Error(1)
}

// Delete provides a mock function with given fields: ctx, id
func (m *MockProductRepository) Delete(ctx context.Context, id int64) error {
	ret := m.Called(ctx, id)
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		return rf(ctx, id)
	}
	return ret.Error(0)
}

// GetByID provides a mock function with given fields: ctx, id
func (m *MockProductRepository) GetByID(ctx context.Context, id int64) (*domain.Product, error) {
	ret := m.Called(ctx, id)
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Product); ok {
		return rf(ctx, id), ret.Error(1)
	}
	var r0 *domain.Product
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*domain.Product)
	}
	return r0, ret.Error(1)
}

// Update provides a mock function with given fields: ctx, id, product
func (m *MockProductRepository) Update(ctx context.Context, id int64, product *domain.Product) error {
	ret := m.Called(ctx, id, product)
	if rf, ok := ret.Get(0).(func(context.Context, int64, *domain.Product) error); ok {
		return rf(ctx, id, product)
	}
	return ret.Error(0)
}

// EXPECT returns a struct that allows to set expectations on the calls and assertions on the mocked behavior
func (m *MockProductRepository) EXPECT() *MockProductRepositoryExpectations {
	return &MockProductRepositoryExpectations{mock: m}
}

type MockProductRepositoryExpectations struct {
	mock *MockProductRepository
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - product *domain.Product
func (e *MockProductRepositoryExpectations) Create(ctx interface{}, product interface{}) *mock.Call {
	return e.mock.On("Create", ctx, product)
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (e *MockProductRepositoryExpectations) Delete(ctx interface{}, id interface{}) *mock.Call {
	return e.mock.On("Delete", ctx, id)
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (e *MockProductRepositoryExpectations) GetByID(ctx interface{}, id interface{}) *mock.Call {
	return e.mock.On("GetByID", ctx, id)
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - product *domain.Product
func (e *MockProductRepositoryExpectations) Update(ctx interface{}, id interface{}, product interface{}) *mock.Call {
	return e.mock.On("Update", ctx, id, product)
}
