// Code generated by mockery v2.40.0. DO NOT EDIT.

package mocks

import (
	"context"
	"testing"

	"github.com/stretchr/testify/mock"

	"project-test-primo/internal/domain"
)

// MockProductUseCase is an autogenerated mock type for the ProductUseCase type
type MockProductUseCase struct {
	mock.Mock
}

// NewProductUseCase creates a new instance of MockProductUseCase.
func NewProductUseCase(t *testing.T) *MockProductUseCase {
	m := &MockProductUseCase{}
	m.Mock.Test(t)
	return m
}

// CreateProduct provides a mock function with given fields: ctx, req
func (m *MockProductUseCase) CreateProduct(ctx context.Context, req *domain.CreateProductRequest) (*domain.Product, error) {
	ret := m.Called(ctx, req)
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateProductRequest) (*domain.Product, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateProductRequest) *domain.Product); ok {
		return rf(ctx, req), ret.Error(1)
	}
	var r0 *domain.Product
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*domain.Product)
	}
	return r0, ret.Error(1)
}

// DeleteProduct provides a mock function with given fields: ctx, id
func (m *MockProductUseCase) DeleteProduct(ctx context.Context, id int64) error {
	ret := m.Called(ctx, id)
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		return rf(ctx, id)
	}
	return ret.Error(0)
}

// GetProduct provides a mock function with given fields: ctx, id
func (m *MockProductUseCase) GetProduct(ctx context.Context, id int64) (*domain.Product, error) {
	ret := m.Called(ctx, id)
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Product); ok {
		return rf(ctx, id), ret.Error(1)
	}
	var r0 *domain.Product
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*domain.Product)
	}
	return r0, ret.Error(1)
}

// UpdateProduct provides a mock function with given fields: ctx, id, updates
func (m *MockProductUseCase) UpdateProduct(ctx context.Context, id int64, updates map[string]interface{}) error {
	ret := m.Called(ctx, id, updates)
	if rf, ok := ret.Get(0).(func(context.Context, int64, map[string]interface{}) error); ok {
		return rf(ctx, id, updates)
	}
	return ret.Error(0)
}

// EXPECT returns a struct that allows to set expectations on the calls and assertions on the mocked behavior
func (m *MockProductUseCase) EXPECT() *MockProductUseCaseExpectations {
	return &MockProductUseCaseExpectations{mock: m}
}

type MockProductUseCaseExpectations struct {
	mock *MockProductUseCase
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.CreateProductRequest
func (e *MockProductUseCaseExpectations) CreateProduct(ctx interface{}, req interface{}) *mock.Call {
	return e.mock.On("CreateProduct", ctx, req)
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (e *MockProductUseCaseExpectations) DeleteProduct(ctx interface{}, id interface{}) *mock.Call {
	return e.mock.On("DeleteProduct", ctx, id)
}

// GetProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (e *MockProductUseCaseExpectations) GetProduct(ctx interface{}, id interface{}) *mock.Call {
	return e.mock.On("GetProduct", ctx, id)
}

// UpdateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - updates map[string]interface{}
func (e *MockProductUseCaseExpectations) UpdateProduct(ctx interface{}, id interface{}, updates interface{}) *mock.Call {
	return e.mock.On("UpdateProduct", ctx, id, updates)
}
